version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Pull submodules"
          command: git submodule update --init
      - run:
          name: "Run tests"
          commands: 
              - time ./aucli --test-full
                  timeout: 1200

