# Based on https://github.com/Alluxio/alluxio/blob/4462fe8b2fb13a59dbd1775219364feae416c82a/integration/kubernetes/alluxio-worker.yaml.template
# We modify the command to set up the required directories (domain socket)
# versus creating them on the host manually.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: alluxio-worker
spec:
  template:
    metadata:
      labels:
        name: alluxio-worker
        app: alluxio
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: alluxio-worker
          image: alluxio/alluxio:1.8.1
          resources:
            requests:
              cpu: "0.5"
              memory: "2G"
            limits:
              cpu: "1"
              memory: "2G"
          command: ["/bin/sh"]
          args: ["-c", "mkdir -p /tmp/alluxio/domain && chmod a+w /tmp/alluxio/domain && touch /tmp/alluxio/domain/d && chmod a+w /tmp/alluxio/domain/d && df -h && /entrypoint.sh worker"]
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          envFrom:
          - configMapRef:
              name: alluxio-config
          ports:
          - containerPort: 29998
            name: rpc
          - containerPort: 29999
            name: data
          - containerPort: 29996
            name: web
          - containerPort: 30001
            name: job-rpc
          - containerPort: 30002
            name: job-data
          - containerPort: 30003
            name: job-web
          securityContext:
            privileged: true
          volumeMounts:
            - name: alluxio-ramdisk
              mountPath: /dev/shm
            - name: alluxio-domain
              mountPath: /tmp/alluxio
      restartPolicy: Always
      volumes:
        - name: alluxio-ramdisk
          emptyDir:
            medium: "Memory"
            sizeLimit: "1G"
        - name: alluxio-domain
          hostPath:
            path: /tmp/aluxio
            type: DirectoryOrCreate

